# Thay đổi thông tin owner
owner: anikenjki  # Thay bằng username của bạn
repo: uptime-page                  # Tên repo vừa tạo

# Các site cần monitor
sites:
  - name: AniKenji Website
    url: https://anikenji.live
    
  - name: Streaming API
    url: https://service.anikenji.live  # Thay bằng endpoint API của bạn
    
# Thông tin status page
status-website:
  cname: status.anikenji.live  # Custom domain
  logoUrl: https://anikenji.live/images/header-logo.png  # Logo của bạn
  name: AniKenji Status
  introTitle: "**AniKenji** đang hoạt động bình thường"
  introMessage: Trang này hiển thị trạng thái realtime của hệ thống AniKenji.
  theme: dark  # hoặc light
  
# Cấu hình thông báo (tùy chọn)
# notifications:
#   - type: discord
#     channel: DISCORD_WEBHOOK_URL
